### PR TITLE
Fix RuntimeException in sonata:admin:explain command

### LINKED ISSUE #164: 'The Request object has not been set' with 'console sonata:admin:explain ...'
## Steps to reproduce

Excecute :

` console sonata:admin:explain ` _service_

## Actual results

>  [RuntimeException]
>  The Request object has not been set

## Solution 

In file "/Admin/Extension/AbstractTranslatableAdminExtension.php" line 71 replace 
```diff
- if ($admin->getRequest()) {
+ if ($admin->hasRequest()) {
    $this->translatableLocale = $admin->getRequest()->get(self::TRANSLATABLE_LOCALE_PARAMETER);
 }
```

### PR DESCRIPTION
**Pull request by dmarkowicz**
I am targeting this branch, because it is bugfix.

Closes #164

## Changelog

```markdown
### Fixed
- Fix RuntimeException in sonata:admin:explain command
```

## Subject
RuntimeException is thrown in `sonata:admin:explain` command and output is truncated.

### CODE REVIEW

File: Admin/Extension/AbstractTranslatableAdminExtension.php [hunk 1]
```diff
@@ -68,7 +68,7 @@ public function getTranslatableChecker()
     public function getTranslatableLocale(AdminInterface $admin)
     {
         if ($this->translatableLocale == null) {
-            if ($admin->getRequest()) {
+            if ($admin->hasRequest()) {
```
Comment (core23) [inline Admin/Extension/AbstractTranslatableAdminExtension.php]: This looks right, but I'm wondering how this exception could occur. `hasRequest` is just a simple wrapper for a null check.

Comment (dmarkowicz) [reply Admin/Extension/AbstractTranslatableAdminExtension.php]: There is no HTTP request in a CLI command.

Comment (core23) [reply Admin/Extension/AbstractTranslatableAdminExtension.php]: I understand the problem, but I don't understand why this could happen...

`if ($admin->hasRequest()) {` 

... would be evaluated to ...

`if ($admin->getRequest() !== null) {`

... which should be the same like ...

`if ($admin->getRequest()) {`

**Comment by core23** [comment]
Thanks @dmarkowicz
