### PR TITLE
Always load TranslatableChecker service

### LINKED ISSUE #673: Enabling knplabs mode without sonata-project/doctrine-orm-admin-bundle causes exception on compiler pass
#### Sonata packages

<details><summary>show</summary>
<p>

sonata-project/admin-bundle         4.22.4  The missing Symfony Admin Generator
sonata-project/block-bundle         4.20.0  Symfony SonataBlockBundle
sonata-project/cache                2.2.0   Cache library
sonata-project/doctrine-extensions  2.2.0   Doctrine2 behavioral extensions
sonata-project/exporter             3.1.1   Lightweight Exporter library
sonata-project/form-extensions      1.18.1  Symfony form extensions
sonata-project/translation-bundle   3.1.0   SonataTranslationBundle
sonata-project/twig-extensions      2.0.0   Sonata twig extensions

</p>
</details>

#### Symfony packages

<details><summary>show</summary>
<p>

symfony/asset                       v6.2.7  Manages URL generation and versioning of web assets such as CSS stylesheets, JavaScript files and image files
symfony/browser-kit                 v6.2.7  Simulates the behavior of a web browser, allowing you to make requests, click on links and submit forms programmatically
symfony/cache                       v6.2.7  Provides extended PSR-6, PSR-16 (and tags) implementations
symfony/cache-contracts             v3.2.1  Generic abstractions related to caching
symfony/config                      v6.2.7  Helps you find, load, combine, autofill and validate configuration values of any kind
symfony/console                     v6.2.7  Eases the creation of beautiful and testable command line interfaces
symfony/css-selector                v6.2.7  Converts CSS selectors to XPath expressions
symfony/debug-bundle                v6.2.7  Provides a tight integration of the Symfony VarDumper component and the ServerLogCommand from MonologBridge into the Symfony full-stack framework
symfony/dependency-injection        v6.2.7  Allows you to standardize and centralize the way objects are constructed in your application
symfony/deprecation-contracts       v3.2.1  A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge             v6.2.7  Provides integration for Doctrine with various Symfony components
symfony/doctrine-messenger          v6.2.7  Symfony Doctrine Messenger Bridge
symfony/dom-crawler                 v6.2.7  Eases DOM navigation for HTML and XML documents
symfony/dotenv                      v6.2.7  Registers environment variables from a .env file
symfony/error-handler               v6.2.7  Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher            v6.2.7  Provides tools that allow your application components to communicate with each other by dispatching events and listening to them
symfony/event-dispatcher-contracts  v3.2.1  Generic abstractions related to dispatching event
symfony/expression-language         v6.2.7  Provides an engine that can compile and evaluate expressions
symfony/filesystem                  v6.2.7  Provides basic utilities for the filesystem
symfony/finder                      v6.2.7  Finds files and directories via an intuitive fluent interface
symfony/flex                        v2.2.5  Composer plugin for Symfony
symfony/form                        v6.2.7  Allows to easily create, process and reuse HTML forms
symfony/framework-bundle            v6.2.7  Provides a tight integration between Symfony components and the Symfony full-stack framework
symfony/http-client                 v6.2.7  Provides powerful methods to fetch HTTP resources synchronously or asynchronously
symfony/http-client-contracts       v3.2.1  Generic abstractions related to HTTP clients
symfony/http-foundation             v6.2.7  Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                 v6.2.7  Provides a structured process for converting a Request into a Response
symfony/intl                        v6.2.7  Provides a PHP replacement layer for the C intl extension that includes additional data from the ICU library
symfony/mailer                      v6.2.7  Helps sending emails
symfony/maker-bundle                v1.48.0 Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/messenger                   v6.2.7  Helps applications send and receive messages to/from other applications or via message queues
symfony/mime                        v6.2.7  Allows manipulating MIME messages
symfony/monolog-bridge              v6.2.7  Provides integration for Monolog with various Symfony components
symfony/monolog-bundle              v3.8.0  Symfony MonologBundle
symfony/notifier                    v6.2.7  Sends notifications via one or more channels (email, SMS, ...)
symfony/options-resolver            v6.2.7  Provides an improved replacement for the array_replace PHP function
symfony/password-hasher             v6.2.7  Provides password hashing utilities
symfony/phpunit-bridge              v6.2.7  Provides utilities for PHPUnit, especially user deprecation notices management
symfony/polyfill-intl-grapheme      v1.27.0 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu           v1.27.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn           v1.27.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer    v1.27.0 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring           v1.27.0 Symfony polyfill for the Mbstring extension
symfony/process                     v6.2.7  Executes commands in sub-processes
symfony/property-access             v6.2.7  Provides functions to read and write from/to an object or array using a simple string notation
symfony/property-info               v6.2.7  Extracts information about PHP class' properties using metadata of popular sources
symfony/routing                     v6.2.7  Maps an HTTP request to a set of configuration variables
symfony/runtime                     v6.2.7  Enables decoupling PHP applications from global state
symfony/security-acl                v3.3.2  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle             v6.2.7  Provides a tight integration of the Security component into the Symfony full-stack framework
symfony/security-core               v6.2.7  Symfony Security Component - Core Library
symfony/security-csrf               v6.2.7  Symfony Security Component - CSRF Library
symfony/security-http               v6.2.7  Symfony Security Component - HTTP Integration
symfony/serializer                  v6.2.7  Handles serializing and deserializing data structures, including object graphs, into array structures or other formats like XML and JSON.
symfony/service-contracts           v3.2.1  Generic abstractions related to writing services
symfony/stopwatch                   v6.2.7  Provides a way to profile code
symfony/string                      v6.2.7  Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters in a unified way
symfony/translation                 v6.2.7  Provides tools to internationalize your application
symfony/translation-contracts       v3.2.1  Generic abstractions related to translation
symfony/twig-bridge                 v6.2.7  Provides integration for Twig with various Symfony components
symfony/twig-bundle                 v6.2.7  Provides a tight integration of Twig into the Symfony full-stack framework
symfony/validator                   v6.2.7  Provides tools to validate values
symfony/var-dumper                  v6.2.7  Provides mechanisms for walking through any arbitrary PHP variable
symfony/var-exporter                v6.2.7  Allows exporting any serializable PHP data structure to plain PHP code
symfony/web-link                    v6.2.7  Manages links between resources
symfony/web-profiler-bundle         v6.2.7  Provides a development tool that gives detailed information about the execution of any request
symfony/yaml                        v6.2.7  Loads and dumps YAML files

</p>
</details>

#### PHP version

8.1.12

## Subject

Enabling knplabs mode without first installing sonata-project/doctrine-orm-admin-bundle causes an exception

## Steps to reproduce

1. Install this bundle
2. enable knplabs mode

## Expected results

No exception, more useful exception or information added to Installation / configuration docs about `sonata-project/doctrine-orm-admin-bundle` being required

## Actual results

```
In CheckExceptionOnInvalidReferenceBehaviorPass.php line 83:
                                                                                                                                                            
  The service "sonata_translation.twig.sonata_translation_extension" has a dependency on a non-existent service "sonata_translation.checker.translatable". 
```

### PR DESCRIPTION
**Pull request by VincentLanglet**
## Subject

Closes #673.

## Changelog

```markdown
### Fixed
- Always load the TranslatableChecker
```

### CODE REVIEW

**Comment by VincentLanglet** [comment]
WDYT about this change @jordisala1991 ?

**Comment by VincentLanglet** [comment]
@olia-bn does this PR solve your issue https://github.com/sonata-project/SonataTranslationBundle/issues/673 ?

File: src/DependencyInjection/SonataTranslationExtension.php [hunk 1]
```diff
@@ -102,6 +102,7 @@ public function load(array $configs, ContainerBuilder $container): void
             $translationTargets['knplabs']['instanceof'] = $listOfClasses;
         }
 
+        $loader->load('checker.php'); // NEXT_MAJOR: Move this line inside the `if`
```
Comment (jordisala1991) [inline src/DependencyInjection/SonataTranslationExtension.php:105]: why dont you add it to the if directly?

Comment (VincentLanglet) [reply src/DependencyInjection/SonataTranslationExtension.php:105]: If you don't enable gedmo or knp, but install doctrine-orm, currently you'll load the checker.
So people might use directly the service in their code for no reason.

If I move this inside the if, you'll get the checker only if one of the gedmo/knp integration is used.

Comment (jordisala1991) [reply src/DependencyInjection/SonataTranslationExtension.php:105]: Then do we really want to restrict that on next major?

Comment (VincentLanglet) [reply src/DependencyInjection/SonataTranslationExtension.php:105]: Don't you consider that having a service declared in 3.1.0 and not anymore in 3.1.1 (or 3.2.0) would be a BC break ?

Comment (jordisala1991) [reply src/DependencyInjection/SonataTranslationExtension.php:105]: Yes, it might be bc break, what I dont understand is why to declare a service that does not have any dep and might be used outside of knp and gedmo, only when gedmo or knp are enabled (the next major comment).

If the service can be used without knp and gedmo I would remove that comment.

Comment (VincentLanglet) [reply src/DependencyInjection/SonataTranslationExtension.php:105]: I was trying to follow the same strategy that for others services
https://github.com/sonata-project/SonataTranslationBundle/blob/3.x/src/Resources/config/block.php
https://github.com/sonata-project/SonataTranslationBundle/blob/3.x/src/Resources/config/listener.php
https://github.com/sonata-project/SonataTranslationBundle/blob/3.x/src/Resources/config/twig.php
which are only loaded conditionally 

But maybe we could load all these services everytime.

**Comment by olia-bn** [comment]
> @olia-bn does this PR solve your issue #673 ?

Yes this fixes the issue I reported.

File: src/DependencyInjection/SonataTranslationExtension.php (hunk 1 above)
Comment (jordisala1991) [reply src/DependencyInjection/SonataTranslationExtension.php:105]: Lets follow same strategy then.

**Review by jordisala1991 — APPROVED** [review]
